image: rustlang/rust:nightly
build:
  stage: build
  script: "cargo --version | tee out.test"
  artifacts:
    paths:
      - out.test

test:
  stage: test
  script: "cat out.test"
  dependencies:
  - build
