build_release:
  image: registry.gitlab.com/dozo/project/rust-server:latest
  stage: build
  script:
    - cd backend/api-server && cargo build
  artifacts:
    paths:
      - backend/api-server/target

test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose -t ./.docker-compose
    - echo build token $CI_BUILD_TOKEN
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - "cd ./.docker-compose && python -m compose -f ../backend/docker-compose.test.yml up -d"
    - docker ps
    - docker ps | grep backend_api-server
    - docker ps | grep backend_api-server | awk '{ print $1 }'
    - docker exec -it $(docker ps | grep backend_api-server | awk '{ print $1 }') "./wait-for-it.sh db:5432 -- diesel setup && cargo test"
  dependencies:
  - build_release

deploy:
  stage: deploy
  script: "echo"
