image: docker:latest

services:
  - docker:dind

build_release:
  stage: build
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose -t ./.docker-compose
    - "cd ./.docker-compose && python -m compose -f ../backend/docker-compose.test.yml up -d api-server"
    - docker exec -it $(docker ps | grep backend_api-server | awk '{ print $1 }') cargo build
  artifacts:
    paths:
      - backend/api-server/target
      - ./.docker-compose

test:
  stage: test
  script:
    - "cd ./.docker-compose && python -m compose -f ../backend/docker-compose.test.yml up"
    - docker exec -it $(docker ps | grep backend_api-server | awk '{ print $1 }') "./wait-for-it.sh db:5432 -- diesel setup && cargo test"
  dependencies:
  - build_release

deploy:
  stage: deploy
  script: "echo"
  dependencies:
  - test
