#build_release:
  #image: registry.gitlab.com/dozo/project/rust-server:latest
  #stage: build
  #script:
    #- cd backend/api-server && cargo build
  #artifacts:
    #paths:
      #- backend/api-server/target

test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose -t ./.docker-compose
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - cd ./.docker-compose
    - python -m compose -f ../backend/docker-compose.test.yml up -d db
    - python -m compose -f ../backend/docker-compose.test.yml run api-server bash -c "DATABASE_URL=$DATABASE_URL SALT_PREFIX=$SALT_PREFIX ./test_server.sh"
  #dependencies:
  #- build_release

deploy:
  stage: deploy
  script:
    - echo "$PRODUCTION_SSH_KEY" > production_key.pem
    - chmod 700 production_key.pem
    - ssh -o StrictHostKeyChecking=no -i production_key.pem $PRODUCTION_SSH_URL "./deploy_server"
  environment:
    name: production
    url: $PRODUCTION_URL
  only:
    - master
