image: rustlang/rust:nightly

build_release:
  stage: build
  script: "cd backend/api-server && cargo build --release"
  artifacts:
    paths:
      - backend/api-server/target

test:
  stage: test
  script: "cd backend/api-server && cargo test --release"
  dependencies:
  - build_release

deploy:
  stage: deploy
  script: "echo"
  dependencies:
  - build_release
