[package]
name = "api-server"
version = "0.1.0"
authors = ["Andrew Li <andrew@pesto-pay.com>", "Saurav Mitra <saurav@pesto-pay.com>", "Fu Yong Quah <fuyong@pesto-pay.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.2"
diesel = { version = "1.1.1", features = ["postgres", "chrono", "r2d2"] }
chrono = { version = "0.4", features = ["rustc-serialize"]}
dotenv = "0.10.0"
r2d2 = "0.8.2"
lazy_static = "0.2.8"
serde = "1.0"
serde_derive = "1.0"
protobuf = "1.4.3"
