[package]
name = "api-server"
version = "0.1.0"
authors = ["Andrew Li <andrewy.li@outlook.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.2"
diesel = { version = "0.15.0", features = ["postgres"] }
diesel_codegen = { version = "0.15.0", features = ["postgres"] }
dotenv = "0.10.0"
r2d2 = "0.7.3"
r2d2-diesel = "0.15.0"
lazy_static = "0.2.8"
serde = "1.0"
serde_derive = "1.0"
protobuf = "1.4.3"
