[global]
address = "0.0.0.0"
port = 3001
template_dir = "static/templates/"
[production]
secret_key = "7e/u6U1PNddvJ6Dhwh18f0X53KaeNru11yWbYdsZAkY="
[production.tls]
certs = "ssl/combo.crt"
key = "ssl/server.key"
