version: "3"

services:
  api-server:
    build: ./api-server
    volumes:
      - ./api-server:/usr/src/app
    links:
      - db
  db:
    image: "postgres:9"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pestodev
      PGDATA: /var/lib/postgresql/data/pgdata
# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
