version: "3"


services:
    api-server:
        build: ./api-server
        ports:
            - "3001:3001"
        volumes:
            - ./api-server:/usr/src/app
        links:
            - db
        command: bash -c "./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"
        environment:
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/dev
    db:
        image: "postgres:9"
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres 
            POSTGRES_DB: dev
            PGDATA: /var/lib/postgresql/data/pgdata

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
    pgdata: {}

