version: "3"

services:
  api-server:
    image: "registry.gitlab.com/dozo/project/rust-server"
    ports:
      - "443:3001"
    volumes:
      - ./api-server:/usr/src/app
    links:
      - db
    environment:
      - OPENSSL_LIB_DIR=/usr/src/app/openssl/lib
      - OPENSSL_INCLUDE_DIR=/usr/src/app/openssl/include
    command: bash -c "./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x 'run --features \"tls notifications\"'"
  db:
    image: "postgres:9"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pestodev
      PGDATA: /var/lib/postgresql/data/pgdata
# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
